In [1]:
# Dhruv Patel
# 10/29/2022
# Assignment #2
# CAC 350
import numpy as np
import random
# Prints 5 rows sliced in 7 colums arranging a random number with 1000 being the max and showcasing the array
np.arange(5) + np.arange(random.randint(1,100), 1000, random.randint(1,100)) [:7, np.newaxis]

array([[ 99, 100, 101, 102, 103],
       [105, 106, 107, 108, 109],
       [111, 112, 113, 114, 115],
       [117, 118, 119, 120, 121],
       [123, 124, 125, 126, 127],
       [129, 130, 131, 132, 133],
       [135, 136, 137, 138, 139]])

In [126]:
# np.arrange returns values within a give interval as numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
# np.newaxis adds a new dimension of size 1 at that position
arrange = np.arange(6)
print (arrange)
print(arrange[:,  np.newaxis])

[0 1 2 3 4 5]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


In [127]:
# np.sort can use any sort quicksort, mergesort,stable,heapsort under the kind catogry labeling the sorting algoritum. numpy.sort(a, axis=-1, kind=None, order=None)
# The speed notation faries are quicksort uses a O(n^2) as the worst mergesort - O(n*log(n)) stable - O(n*log(n)) heapsort - O(n*log(n)). the Big O represent the speed of the execution within data structure and algoritums depending on the sort method.
sort = np.array([[1,4],[3,1]])
np.sort(sort)
np.sort(sort, axis=None)
#np.sort(sort, axis=0)

array([1, 1, 3, 4])

In [128]:
# Prints sorted array
array = [4,1,5,2,7,3]
np.sort(array)

array([1, 2, 3, 4, 5, 7])

In [129]:
# Sorts colums according to the first axis in order of first order.
columns = np.array([[1,3],[4,5],[3,2],[0,6]])
np.sort(columns, axis=1)   



array([[1, 3],
       [4, 5],
       [2, 3],
       [0, 6]])

In [130]:
# Sorts rows according to the 0 axis in order of the second order
rows = np.array([[1,3],[4,5],[3,2],[0,6]])
np.sort(rows, axis=0)

array([[0, 2],
       [1, 3],
       [3, 5],
       [4, 6]])

In [131]:
# Structured Array - It is used for grouping data of different arrays for types and sizes using data containers containing arrays of different data type.

In [132]:
#Import pandas and NumPy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Reads the file and prints the csv colums and info of the first 5 for carData1
carData1= pd.read_csv('cars1.csv')
carData1.head()



mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70   
1  15.0          8           350        165    3693          11.5     70   
2  18.0          8           318        150    3436          11.0     70   
3  16.0          8           304        150    3433          12.0     70   
4  17.0          8           302        140    3449          10.5     70   

   origin                        car  Unnamed: 9  Unnamed: 10  Unnamed: 11  \
0       1  chevrolet chevelle malibu         NaN          NaN          NaN   
1       1          buick skylark 320         NaN          NaN          NaN   
2       1         plymouth satellite         NaN          NaN          NaN   
3       1              amc rebel sst         NaN          NaN          NaN   
4       1                ford torino         NaN          NaN          NaN   

   Unnamed: 12  Unnamed: 13  
0          NaN          NaN  
1          NaN          NaN  
2          NaN          NaN  
3          NaN          NaN  
4          NaN          NaN

In [133]:
#Reads the file and prints the csv colums and info of the first 5 for carData2
carData2 = pd.read_csv('cars2.csv')
carData2.head()

# 9 each oberservation for each dataset

mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  33.0          4            91         53    1795          17.4     76   
1  20.0          6           225        100    3651          17.7     76   
2  18.0          6           250         78    3574          21.0     76   
3  18.5          6           250        110    3645          16.2     76   
4  17.5          6           258         95    3193          17.8     76   

   origin                 car  
0       3         honda civic  
1       1      dodge aspen se  
2       1   ford granada ghia  
3       1  pontiac ventura sj  
4       1       amc pacer d/l

In [134]:
# Removes all unamed columns
carData1 = carData1.loc[:, ~carData1.columns.str.contains('^Unnamed')]
carData2 = carData2.loc[:, ~carData2.columns.str.contains('^Unnamed')]

In [135]:
# Merges the two data
#mergedCarData = pd.merge(carData1, carData2, on = 'mpg' , how = 'inner')
#mergedCarData = pd.concat(carData1, carData2, join = 'outer')
#print(mergedCarData)

frames = [carData1, carData2]
mergedCarData = pd.concat(frames)

In [136]:
# Show cases each colums merged
import random
mergedCarData.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model', 'origin', 'car'],
      dtype='object')

In [137]:
owner = np.random.randint(15000,73000, 398)
mergedCarData["Owner"] = owner
mergedCarData.head()


mpg  cylinders  displacement horsepower  weight  acceleration  model  \
0  18.0          8           307        130    3504          12.0     70   
1  15.0          8           350        165    3693          11.5     70   
2  18.0          8           318        150    3436          11.0     70   
3  16.0          8           304        150    3433          12.0     70   
4  17.0          8           302        140    3449          10.5     70   

   origin                        car  Owner  
0       1  chevrolet chevelle malibu  24970  
1       1          buick skylark 320  61770  
2       1         plymouth satellite  72168  
3       1              amc rebel sst  41015  
4       1                ford torino  58266

In [141]:
carmpg = mergedCarData["mpg"]
carhorsepower = mergedCarData["displacement"]
minimum = min(carmpg)
maximum = max(carhorsepower)
carModel = pd.Series([0,8])

print("The lowest mpg car has a min mpg of", minimum )
print("The highest horesepower has a max power of", maximum)

The lowest mpg car has a min mpg of 9.0
The highest horesepower has a max power of 455
